class DatosTabla {
  static final List<Map<String, dynamic>> filas = [
    {
      'number': 1,
      'pad': '145',
      'placa': 'XYZ-456',
      'h_ini': '05:20',
      // SIN DATOS
      'con1': '',
      'con2': '-4',
      'con3': '+3',
      'con4': '-5',
      'con5': '-5',
      // NO EXISTE EL VALOR
      //'con6': '0',
      'total': '+70',
      'terminal': '',
      'conductor': 'Carlos Martínez López',
      'cobrador': 'Ana García Rodríguez'
    },
    {
      'number': 2,
      'pad': '112',
      'placa': 'DEF-789',
      'h_ini': '06:15',
      'con1': '+5',
      'con2': '+5',
      'con3': '+5',
      'con4': '0',
      'con5': '+5',
      'con6': '+5',
      'total': '+42',
      'terminal': 'A',
      'conductor': 'María Fernández Sánchez',
      'cobrador': 'Pedro Ramírez Torres'
    },
    {
      'number': 3,
      'pad': '156',
      'placa': 'GHI-234',
      'h_ini': '04:45',
      'con1': '+5',
      'con2': '0',
      'con3': '+5',
      'con4': '+5',
      'con5': '+5',
      'con6': '+5',
      'total': '+12',
      'terminal': 'A',
      'conductor': 'Luis Alberto Morales',
      'cobrador': 'Sofía Núñez Gutiérrez'
    },
    {
      'number': 4,
      'pad': '133',
      'placa': 'JKL-567',
      'h_ini': '05:10',
      'con1': '-5',
      'con2': '-5',
      'con3': '-5',
      'con4': '-5',
      'con5': '-5',
      'con6': '+5',
      'total': '+11',
      'terminal': 'B',
      'conductor': 'Elena Ruiz Pérez',
      'cobrador': 'Diego Hernández Castro'
    },
    {
      'number': 5,
      'pad': '167',
      'placa': 'MNO-890',
      'h_ini': '06:00',
      'con1': '+5',
      'con2': '+5',
      'con3': '+5',
      'con4': '+5',
      'con5': '+5',
      'con6': '+5',
      'total': '+36',
      'terminal': 'B',
      'conductor': 'Javier Torres Moreno',
      'cobrador': 'Laura Díaz Romero'
    },
    {
      'number': 6,
      'pad': '121',
      'placa': 'PQR-123',
      'h_ini': '04:55',
      'con1': '-5',
      'con2': '0',
      'con3': '-5',
      'con4': '-5',
      'con5': '-5',
      'con6': '+5',
      'total': '+4',
      'terminal': 'B',
      'conductor': 'Adriana Gómez Herrera',
      'cobrador': 'Roberto Jiménez Navarro'
    },
    {
      'number': 7,
      'pad': '178',
      'placa': 'STU-456',
      'h_ini': '05:40',
      'con1': '+5',
      'con2': '+5',
      'con3': '+5',
      'con4': '0',
      'con5': '+5',
      'con6': '+5',
      'total': '+10',
      'terminal': 'B',
      'conductor': 'Fernando Vargas Lara',
      'cobrador': 'Claudia Mendoza Ríos'
    },
    {
      'number': 8,
      'pad': '109',
      'placa': 'VWX-789',
      'h_ini': '06:30',
      'con1': '-5',
      'con2': '-5',
      'con3': '-5',
      'con4': '-5',
      'con5': '-5',
      'con6': '+36',
      'total': '+1',
      'terminal': 'B',
      'conductor': 'Raquel Soto Castillo',
      'cobrador': 'Miguel Ángel Cruz León'
    },
    {
      'number': 9,
      'pad': '142',
      'placa': 'YZA-012',
      'h_ini': '05:05',
      'con1': '+5',
      'con2': '+5',
      'con3': '+5',
      'con4': '+5',
      'con5': '+5',
      'con6': '+5',
      'total': '+0',
      'terminal': 'A',
      'conductor': 'Beatriz Ortiz Guerrero',
      'cobrador': 'Andrés Medina Cortés'
    },
    {
      'number': 10,
      'pad': '115',
      'placa': 'BCD-345',
      'h_ini': '04:50',
      'con1': '-5',
      'con2': '-5',
      'con3': '-5',
      'con4': '-5',
      'con5': '-5',
      'con6': '+42',
      'total': '+70',
      'terminal': 'A',
      'conductor': 'Ricardo Navarro Fuentes',
      'cobrador': 'Patricia Alvarez Ramos'
    }
  ];
}